apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ping-server
  namespace: probes
spec:
  endpoints:
    - interval: 30s
      port: metrics
  namespaceSelector:
    matchNames:
      - probes
  selector:
    matchLabels:
      probe: ping-server
