apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: cilium
  labels:
    k8s-app: cilium
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9090
  selector:
    k8s-app: cilium
