apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-k8s-rules
  namespace: monitoring
spec:
  groups:
  - name: apiserver.rules
    rules:
    - expr: |
        histogram_quantile(0.99, sum(rate(apiserver_request_latency_seconds_bucket[5m])) by (resource,  subresource, verb, scope, le))
      record: apiserver:apiserver_request_latency:histogram_quantile
      labels:
        quantile: "0.99"
    - expr: |
        histogram_quantile(0.9, sum(rate(apiserver_request_latency_seconds_bucket[5m])) by (resource,  subresource, verb, scope, le))
      record: apiserver:apiserver_request_latency:histogram_quantile
      labels:
        quantile: "0.90"
    - expr: |
        histogram_quantile(0.5, sum(rate(apiserver_request_latency_seconds_bucket[5m])) by (resource,  subresource, verb, scope, le))
      record: apiserver:apiserver_request_latency:histogram_quantile
      labels:
        quantile: "0.50"
  - name: probes.rules
    rules:
    - expr: |
        histogram_quantile(0.99, sum(rate(probes_in_cluster_network_latency_seconds_bucket[5m])) by (le))
      record: probes:in_cluster_network_latency:histogram_quantile
      labels:
        quantile: "0.99"
    - expr: |
        histogram_quantile(0.90, sum(rate(probes_in_cluster_network_latency_seconds_bucket[5m])) by (le))
      record: probes:in_cluster_network_latency:histogram_quantile
      labels:
        quantile: "0.90"
    - expr: |
        histogram_quantile(0.50, sum(rate(probes_in_cluster_network_latency_seconds_bucket[5m])) by (le))
      record: probes:in_cluster_network_latency:histogram_quantile
      labels:
        quantile: "0.50"
