apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    name: {{.Name}}
spec:
  clusterIP: None
  selector:
    name: {{.Name}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Name}}
spec:
  selector:
    matchLabels:
      group: statefulset
      name: {{.Name}}
  serviceName: {{.Name}}
  replicas: {{.Replicas}}
  template:
    metadata:
      labels:
        group: statefulset
        name: {{.Name}}
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: {{.Name}}
        image: k8s.gcr.io/pause:3.1
        ports:
          - containerPort: 80
            name: web
        resources:
          requests:
            cpu: 10m
            memory: "10M"
